name: Canary release

on: workflow_dispatch

jobs:
  canary-publish:
    name: Publish Packages (canary)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - run: yarn build
      - run: pwd && ls
      - run: cd dist
      - run: pwd && ls
      - run: pwd && ls && yarn version --new-version "0.0.0-${GITHUB_SHA::8}" --no-git-tag-version
      - run: pwd && ls && npm publish --access public --tag canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
