# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]

jobs:
  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18]
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Add Git to PATH
        run: |
          echo "PATH=$PATH:/c/Program Files/Git" >> $GITHUB_ENV
      - run: yarn --version
      - run: yarn --frozen-lockfile
      - run: yarn test

